[build]
  # Tell Netlify where the serverless functions are located
  functions = "functions"

[[redirects]]
  # Redirect all requests to the serverless function
  from = "/working-location"
  to = "/.netlify/functions/working-location"
  status = 200
