[build]
  # No build command since you are deploying only functions
  functions = "functions"  # Point to your functions directory

[[redirects]]
  from = "/working-location"
  to = "/.netlify/functions/working-location"
  status = 200
